[package]
name = "randomduck/hugo-starter-b02"
version = "0.2.1"
description = "Wasmer Hugo starter package"
readme = "README.md"
repository = "https://github.com/ayys/hugo-starter-b02"

[dependencies]
"wasmer/static-web-server" = "^1"

[fs]
public = "public"
